[person]
  name = "John Doe"
  age = 30

  [person.address]
    street = "123 Main St"
    city = "Anytown"
    state = "CA"

    [person.address.zip]
      code = "12345"
      extension = "6789"

  [person.contacts]
    [person.contacts.email]
      type = "work"
      address = "jdoe@acme.com"

    [person.contacts.phone]
      type = "home"
      number = "555-1234"
      extension = "5678"